setFarClipDistance(5000)
setFogDistance(5000)

addCommandHandler("gp",function() 
    outputChatBox("Interior: " .. getElementInterior(localPlayer) .. " Dimension: " .. getElementDimension(localPlayer))
    local x,y,z = getElementPosition(localPlayer)
    p = string.format("%.2f, %.2f, %.2f", x,y,z)
	local rx,ry,yz = getElementRotation(localPlayer)
	pp = string.format("%.1f, %.1f, %.1f", rx, ry, yz)
    outputChatBox("Pozycja gracza: ".. p)
    setClipboard(p)
    
    local pojazd = getPedOccupiedVehicle(localPlayer)
    if pojazd then
        local x,y,z = getElementPosition(pojazd)
        local rx,ry,yz = getElementRotation(pojazd)
        p = string.format("%.2f, %.2f, %.2f", x, y, z)
        pp = string.format("%.1f, %.1f, %.1f", rx, ry, yz) 
        outputChatBox("Pozycja pojazdu: ".. p.." Rotacja: "..pp)
        setClipboard(p..", "..pp)
    end
end)
addCommandHandler("be",function() 
    outputChatBox("Interior: " .. getElementInterior(localPlayer) .. " Dimension: " .. getElementDimension(localPlayer))
    local x,y,z = getElementPosition(localPlayer)
    p = string.format("%.2f, %.2f, %.2f", x,y,z)
	local rx,ry,yz = getElementRotation(localPlayer)
	pp = string.format("%.1f, %.1f, %.1f", rx, ry, yz)
    outputChatBox("Pozycja gracza: ".. p)
    setClipboard("{"..p.."},")
    
    local pojazd = getPedOccupiedVehicle(localPlayer)
    if pojazd then
        local x,y,z = getElementPosition(pojazd)
        local rx,ry,yz = getElementRotation(pojazd)
        p = string.format("%.2f, %.2f, %.2f", x, y, z)
        pp = string.format("%.1f, %.1f, %.1f", rx, ry, yz) 
        outputChatBox("Pozycja pojazdu: ".. p.." Rotacja: "..pp)
        setClipboard("{"..p.."},")
    end
end)
unbindKey("G","down","chatbox","global")
unbindKey("U","down","chatbox","global")
unbindKey("F2","down","chatbox","global")
bindKey("F3","down","chatbox","globalchat")
